# name
name: hello_world

# trigger
on:
- push

# one or more jobs
jobs:
   greetings:
     runs-on: ubuntu-latest
     steps:
     - id: s00
       name: Say Hello
       # running some bash command in linux
       run: echo "current time in github is $(date), ${GITHUB_OUTPUT}"
     - id: s01
       # create a value to pass to next step
       run: echo "CURR_DATE=$(date)" >> $GITHUB_OUTPUT
     - id: s02
       uses: mscoutermarsh/cowsays-action@master
       with:
          text: 'Moo moo cow! ${{ steps.s01.outputs.CURR_DATE}}, ${{ github.ref}}, ${{github.repository}}'
          color: 'red'

     # - id: s01
     #   run: ls -al
     # - id: s02
     #   run: cat hello.txt
