# name
name: hello_world

# trigger
on:
- push

# one or more jobs
jobs:
   greetings:
     runs-on: ubuntu-latest
     steps:
     - id: s00
       name: Say Hello
       # running some bash command in linux
       run: echo "current time in github is $(date)"
     - id: s01
       run: ls -al
     - id: s02
       run: cat hello.txt
